import Head from "next/head";
import styles from "../styles/Home.module.css";
import LookforRecipe from "../component/LookforRecipe";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Low carb Recipies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Heatly, a Low Carb Recipy app
        </h1>

        <p className={styles.description}>Get started</p>
        <LookforRecipe></LookforRecipe>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span className={styles.logo}></span>
        </a>
      </footer>
    </div>
  );
}
